import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <script dangerouslySetInnerHTML={{
          __html: `var whTooltips = { colorLinks: true, iconizeLinks: true, renameLinks: true, domain: 'classic' };`
        }} />
      </head>
      <body className="min-h-full flex flex-col">
        {children}
        <Script 
          src="https://wow.zamimg.com/js/tooltips.js" 
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}
